--Installer
function github (url, path)
local content = http.get (url)
local file = fs.open (path,"w")
file.write(content.readAll ())
file.close ()
end

github ("https://github.com/Endergreen117/Synt-OS","")

term.setCursorPos("1,1")
print ("Files downloaded, rebooting in 5..")
sleep (1)
term.setCursorPos ("1,1")
print ("Files downloaded, rebooting in 4..")
sleep (1)
term.setCursorPos ("1,1")
print ("Files downloaded, rebooting in 3..")
sleep (1)
term.setCursorPos ("1,1")
print ("Files downloaded, rebooting in 2..")
sleep (1)
term.setCursorPos ("1,1")
print ("Files downloaded, rebooting in 1..")
sleep (1)
term.setCursorPos ("1,1")
print ("Files downloaded, rebooting NOW!")
sleep (1)
os.reboot ()